# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centered_kernel_matrix <- function(first_vec_kernel, second_vec_kernel, centering_grid, hurst_coef) {
    .Call(`_kef_centered_kernel_matrix`, first_vec_kernel, second_vec_kernel, centering_grid, hurst_coef)
}

density_at_sampled_x <- function(centered_kernel_mat_at_sampled, lambda_hat, weight_hat_vec) {
    .Call(`_kef_density_at_sampled_x`, centered_kernel_mat_at_sampled, lambda_hat, weight_hat_vec)
}

density_at_grid <- function(centered_kernel_mat_at_grid, centered_kernel_self_grid, lambda_hat, weight_hat_vec) {
    .Call(`_kef_density_at_grid`, centered_kernel_mat_at_grid, centered_kernel_self_grid, lambda_hat, weight_hat_vec)
}

get_dens_wo_grid <- function(centered_kernel_mat_at_sampled, min_x, max_x, sampled_x, lambda_hat, weight_hat_vec) {
    .Call(`_kef_get_dens_wo_grid`, centered_kernel_mat_at_sampled, min_x, max_x, sampled_x, lambda_hat, weight_hat_vec)
}

get_dens_or_prob <- function(centered_kernel_mat_at_sampled, centered_kernel_mat_at_grid, centered_kernel_self_grid, sampled_x, x_grid, lambda_hat, weight_hat_vec, type_of_p_is_prob = TRUE, type_of_q_is_prob = TRUE) {
    .Call(`_kef_get_dens_or_prob`, centered_kernel_mat_at_sampled, centered_kernel_mat_at_grid, centered_kernel_self_grid, sampled_x, x_grid, lambda_hat, weight_hat_vec, type_of_p_is_prob, type_of_q_is_prob)
}

get_middle_points_grid <- function(min, samples, max) {
    .Call(`_kef_get_middle_points_grid`, min, samples, max)
}

get_s_function <- function(weight_hat_vec, lambda_hat, tau_hat, centered_kernel_mat_at_sampled, sampled_x, min_x, max_x) {
    .Call(`_kef_get_s_function`, weight_hat_vec, lambda_hat, tau_hat, centered_kernel_mat_at_sampled, sampled_x, min_x, max_x)
}

